Repository kyma-incubator/marketplaces, pull requests merged in 2019-08, with the labels that each got.

#22 Fix link to contributing agreements
  .github/pull-request-template.md
Labels: area/documentation, bug

#23 Update the instruction on connecting the certificate
  google-cloud/manifest/application.yaml
Labels: area/documentation

#24 Switch to Kyma 1.4.0
  KYMA_VERSION
  google-cloud/manifest/application.yaml
Labels: area/community, area/installation, enhancement

#25 Update the access Kyma cluster instruction
  google-cloud/manifest/application.yaml
Labels: area/documentation

#26 Migrate to Kyma 1.4.1
  KYMA_VERSION
Labels: area/community, area/installation, enhancement
